[[main]]
none = "none"

[[main]]
name = "Games"
pageRef = "Games"
weight = 10

[[main]]
name = "Socratic Smackdown"
pageRef = "Games/socratic-smackdown"
parent = "Games"
weight = 10

[[main]]
name = "Belgian Feather Bowling : On the Go!"
pageRef = "Games/bfb"
parent = "Games"
weight = 20

[[main]]
name = "Croaky Climber"
pageRef = "Games/croaky-climber"
parent = "Games"
weight = 30


[[footer]]
none = "none"
